title: Caio Velasco
logo: /assets/img/caio_ucla.JPG
email: caiocvelasco at gmail dot com
description: ""
blank_title: true
show_downloads: false
google_analytics: G-TWEB84PHGE
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-target-blank

sidebar:
  - name: CV
    icon: fa-regular fa-circle-user
    link: /assets/img/en_CV_CaioVelasco_2026.pdf
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/caiocvelasco
  - name: LinkedIn
    icon: fa-brands fa-linkedin
    link: https://www.linkedin.com/in/caiovelasco/
  - name: Project Repository
    icon: fa-solid fa-box-archive
    link: https://github.com/caiocvelasco/caiocvelasco.github.io
